import json
import re
from typing import Dict, Any, List, Optional

PRIVILEGES = ["generate_js_code", "analyze_frontend"]

class JavaScriptTSGenerator:
    """Advanced JavaScript/TypeScript code generator for modern web development"""
    
    # JS/TS-specific templates
    JS_TEMPLATES = {
        'general_js': {
            'imports': ['// ES6+ JavaScript'],
            'template': '''// Modern JavaScript Example
const example = () => {
    console.log("Hello, World!");
    return "Welcome to JavaScript!";
};

example();''',
            'usage': 'General JavaScript development'
        },
        'react_component': {
            'imports': ['import React, { useState, useEffect } from "react";'],
            'template': '''const ComponentName = () => {
  const [state, setState] = useState(initialValue);
  
  useEffect(() => {
    // Component initialization
  }, []);
  
  return (
    <div>
      <h1>Component Name</h1>
      <p>State: {state}</p>
    </div>
  );
};

export default ComponentName;''',
            'usage': 'React functional components with hooks'
        },
        'node_api': {
            'imports': ['const express = require("express");', 'const app = express();'],
            'template': '''const express = require('express');
const app = express();

app.use(express.json());

app.get('/api/endpoint', (req, res) => {
  res.json({ message: 'API response', data: req.body });
});

app.listen(3000, () => {
  console.log('Server running on port 3000');
});''',
            'usage': 'Node.js Express API endpoints'
        }
    }
    
    def __init__(self, request: str):
        self.request = request.lower().strip()
        self.js_type = self._detect_js_type()
        self.framework = self._detect_framework()
        self.is_typescript = self._detect_typescript()
        
    def _detect_js_type(self) -> str:
        """Detect JavaScript/TypeScript task type"""
        if any(word in self.request for word in ['react', 'component', 'jsx']):
            return 'react_component'
        elif any(word in self.request for word in ['api', 'endpoint', 'server', 'express']):
            return 'node_api'
        elif any(word in self.request for word in ['interface', 'type', 'typescript']):
            return 'typescript_interface'
        elif any(word in self.request for word in ['async', 'await', 'promise']):
            return 'async_operations'
        elif any(word in self.request for word in ['vue', 'angular', 'svelte']):
            return 'modern_js'
        else:
            return 'general_js'
    
    def _detect_framework(self) -> str:
        """Detect JS framework preference"""
        if any(word in self.request for word in ['react', 'next', 'gatsby']):
            return 'react'
        elif any(word in self.request for word in ['vue', 'nuxt']):
            return 'vue'
        elif any(word in self.request for word in ['angular']):
            return 'angular'
        elif any(word in self.request for word in ['node', 'express', 'backend']):
            return 'nodejs'
        else:
            return 'vanilla'
    
    def _detect_typescript(self) -> bool:
        """Detect if TypeScript is requested"""
        type_keywords = ['typescript', 'ts', 'interface', 'type:', 'strict']
        return any(keyword in self.request for keyword in type_keywords)
    
    def generate_js_structure(self) -> Dict[str, Any]:
        """Generate JS/TS code structure"""
        template = self.JS_TEMPLATES.get(self.js_type, self.JS_TEMPLATES['general_js'])
        
        return {
            'js_type': self.js_type,
            'framework': self.framework,
            'is_typescript': self.is_typescript,
            'imports': template['imports'],
            'template': template['template'],
            'usage': template['usage'],
            'enhancements': [
                'Error boundary implementation',
                'Performance optimization',
                'Accessibility features',
                'Security best practices',
                'Testing integration'
            ],
            'best_practices': [
                'ES6+ modern syntax',
                'Proper error handling',
                'Code splitting and lazy loading',
                'Performance monitoring',
                'Type safety with TypeScript'
            ]
        }

def generate_enhanced_js_code(analysis: JavaScriptTSGenerator) -> str:
    """Generate enhanced JavaScript/TypeScript code"""
    structure = analysis.generate_js_structure()
    
    header = f"""# JavaScript/TypeScript Code Generator
# Task: {structure['js_type'].replace('_', ' ').title()}
# Framework: {structure['framework'].title()}
# TypeScript: {'Yes' if structure['is_typescript'] else 'No'}
# Generated by Enhanced AI System

"""
    
    imports = "\n".join(structure['imports']) + "\n\n"
    
    main_code = f"""{structure['template']}

// Additional enhancements:
{chr(10).join(f"// - {practice}" for practice in structure['best_practices'])}
"""
    
    enhancements = f"""
# Enhancement Features:
{chr(10).join(f"# - {enhancement}" for enhancement in structure['enhancements'])}

# Modern JavaScript/TypeScript Best Practices:
# - ES6+ syntax with arrow functions
# - Proper async/await patterns
# - Type safety with TypeScript
# - Error boundary implementation
# - Performance optimization
# - Accessibility compliance
"""
    
    return header + imports + main_code + enhancements

def run(input_data="[<input_data>]", user_id="[<user_id>]", session_id="[<session_id>]", model_name="[<model_name>]"):
    """
    Enhanced JavaScript/TypeScript mode: Generate modern web development code
    """
    try:
        if isinstance(input_data, str):
            request_text = input_data
        else:
            request_text = str(input_data)
        
        # Create JS/TS generator instance
        generator = JavaScriptTSGenerator(request_text)
        
        # Generate enhanced JS/TS code
        generated_code = generate_enhanced_js_code(generator)
        structure = generator.generate_js_structure()
        
        response = {
            'request': request_text,
            'analysis': {
                'js_type': generator.js_type,
                'framework': generator.framework,
                'is_typescript': generator.is_typescript
            },
            'generated_code': generated_code,
            'js_structure': structure,
            'framework_info': {
                'recommended_packages': structure['imports'],
                'usage_guide': structure['usage'],
                'best_practices': structure['best_practices']
            },
            'ai_enhancement': {
                'modern_patterns': ['Hooks', 'Context API', 'Redux', 'Zustand'],
                'performance': ['Code splitting', 'Lazy loading', 'Memoization'],
                'testing': ['Jest', 'React Testing Library', 'Cypress']
            }
        }
        
        # Try to enhance with AI model if available
        try:
            from ai_backend.ai_models import models
            model = models.get(model_name)
            if model:
                ai_enhanced = model.generate(
                    f"Generate modern JavaScript/TypeScript code for: {request_text}. "
                    f"Include proper error handling, performance optimization, and best practices.",
                    user_id=user_id, session_id=session_id
                )
                response['ai_enhanced_code'] = ai_enhanced
        except:
            pass
        
        return json.dumps(response, indent=2)
        
    except Exception as e:
        return json.dumps({
            'error': str(e),
            'fallback': 'JavaScript/TypeScript code generation failed.',
            'basic_template': '// Basic JS/TS template\nconst hello = () => console.log("Hello World!");\nhello();'
        })

def javascript_response(prompt: str) -> str:
    """Legacy function for backward compatibility"""
    generator = JavaScriptTSGenerator(prompt)
    structure = generator.generate_js_structure()
    return f"[JavaScript/TS Mode]\nType: {generator.js_type}\nFramework: {generator.framework}\nTypeScript: {generator.is_typescript}\nGenerated: {len(structure.get('enhancements', []))} enhancement features"
